const CITY_TO_IATA: Record<string, string> = {
  "buenos aires": "EZE",
  madrid: "MAD",
  barcelona: "BCN",
  paris: "CDG",
  londres: "LHR",
  london: "LHR",
  roma: "FCO",
  rome: "FCO",
  milan: "MXP",
  lisboa: "LIS",
  lisbon: "LIS",
  amsterdam: "AMS",
  berlin: "BER",
  "nueva york": "JFK",
  "new york": "JFK",
  miami: "MIA",
  "los angeles": "LAX",
  "san francisco": "SFO",
  chicago: "ORD",
  mexico: "MEX",
  "ciudad de mexico": "MEX",
  "mexico city": "MEX",
  cancun: "CUN",
  bogota: "BOG",
  lima: "LIM",
  santiago: "SCL",
  montevideo: "MVD",
  "rio de janeiro": "GIG",
  "sao paulo": "GRU",
  cartagena: "CTG",
  quito: "UIO",
  "la paz": "LPB",
  asuncion: "ASU",
  "punta cana": "PUJ",
  "la habana": "HAV",
  havana: "HAV",
  toronto: "YYZ",
  vancouver: "YVR",
  tokio: "HND",
  tokyo: "HND",
  seul: "ICN",
  seoul: "ICN",
  bangkok: "BKK",
  singapur: "SIN",
  singapore: "SIN",
  dubai: "DXB",
  estambul: "IST",
  istanbul: "IST",
  atenas: "ATH",
  athens: "ATH",
  viena: "VIE",
  vienna: "VIE",
  praga: "PRG",
  prague: "PRG",
  budapest: "BUD",
  dublin: "DUB",
  zurich: "ZRH",
  munich: "MUC",
  frankfurt: "FRA",
  bruselas: "BRU",
  brussels: "BRU",
  sydney: "SYD",
  melbourne: "MEL",
  auckland: "AKL",
  "el cairo": "CAI",
  cairo: "CAI",
  marrakech: "RAK",
  johannesburgo: "JNB",
  "cape town": "CPT",
  "ciudad del cabo": "CPT",
  "parque nacional kruger": "MQP",
  kruger: "MQP",
  "kruger national park": "MQP",
};

function normalize(city: string): string {
  return city
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

export function getAirportCode(city: string): string | undefined {
  return CITY_TO_IATA[normalize(city)];
}
