"""add booking_token to flights

Revision ID: b746df31b94b
Revises: bc59846c149a
Create Date: 2026-08-24 11:10:53.395983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b746df31b94b'
down_revision: Union[str, Sequence[str], None] = 'bc59846c149a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('booking_token', sa.String(), nullable=False))
    # ### end Alembic commands ###
    # NOTA: autogenerate también detectó drops de 'checkpoints', 'checkpoint_blobs',
    # 'checkpoint_writes', 'checkpoint_migrations' y 'token_blocklist' — mismo drift
    # preexistente ya documentado en la migración bc59846c149a, sin relación con este
    # cambio. Se omiten intencionalmente para no dropear datos vivos por error.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'booking_token')
    # ### end Alembic commands ###
