"""add flights table

Revision ID: bc59846c149a
Revises: 51a14e9a036d
Create Date: 2026-08-22 20:17:36.829405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc59846c149a'
down_revision: Union[str, Sequence[str], None] = '51a14e9a036d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('passengers', sa.JSON(), nullable=False),
    sa.Column('journeys', sa.JSON(), nullable=False),
    sa.Column('booking_options', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(), server_default='serpapi', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.itinerary_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_itinerary_id'), 'flights', ['itinerary_id'], unique=False)
    # NOTA: autogenerate también detectó drops de 'checkpoints', 'checkpoint_blobs',
    # 'checkpoint_writes', 'checkpoint_migrations' y 'token_blocklist' — drift
    # preexistente de tablas no modeladas en SQLAlchemy (checkpointer de langgraph,
    # token blocklist), sin relación con esta migración. Se omiten intencionalmente
    # para no dropear datos vivos por error.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_itinerary_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
